<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>razorstyle</ToolCommandName>
    <PackageId>PinguApps.RazorStyle.Cli</PackageId>
    <Description>Command-line formatter and linter for Razor.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PinguApps.RazorStyle.Core\PinguApps.RazorStyle.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
