<Project>
  <PropertyGroup>
    <RazorStyleEnabled Condition="'$(RazorStyleEnabled)' == ''">true</RazorStyleEnabled>
    <RazorStyleCommand Condition="'$(RazorStyleCommand)' == '' and '$(ContinuousIntegrationBuild)' == 'true'">check</RazorStyleCommand>
    <RazorStyleCommand Condition="'$(RazorStyleCommand)' == ''">fix</RazorStyleCommand>
    <DisablePARS0001 Condition="'$(DisablePARS0001)' == ''">false</DisablePARS0001>
    <DisablePARS0002 Condition="'$(DisablePARS0002)' == ''">false</DisablePARS0002>
    <DisablePARS0003 Condition="'$(DisablePARS0003)' == ''">false</DisablePARS0003>
  </PropertyGroup>
</Project>
