name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: pull-request-validation-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/_run-tests.yml
    with:
      publish_test_results_comment_mode: always
      publish_test_results_check_name: Pull Request Test Results
